title: Bienvenidos a mi blog
author: Gabriel A. Luis Freitas
email: alu0101348421@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  Este es un repositorio de pruebas para el curso de github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
